language: java
jdk:
- oraclejdk8
branches:
  only:
    - master
before_deploy:
  - git config --global user.email ${GITHUB_EMAIL}
  - git config --global user.name ${GITHUB_NAME}
  - git tag ${TRAVIS_BUILD_NUMBER}
  - git push -q ${REPO} --tags
deploy:
  provider: releases
  api_key: ${DEPLOY_REPO}
  file:
  - HMCL/build/libs/HMCL-${HMCL_VERSION_ROOT}.${TRAVIS_BUILD_NUMBER}.jar
  - HMCL/build/libs/HMCL-${HMCL_VERSION_ROOT}.${TRAVIS_BUILD_NUMBER}.exe
  - HMCL/build/libs/HMCL-${HMCL_VERSION_ROOT}.${TRAVIS_BUILD_NUMBER}-MacOSApp.zip
  on:
    repo: huanghongxun/HMCL
    tags: false
  skip_cleanup: true
install: echo "skip 'gradle assemble' step"
script: gradle build --continue --debug
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
