language: java
jdk:
- oraclejdk8
branches:
  only:
    - master
before_deploy:
  - git config --global user.email ${GITHUB_EMAIL}
  - git config --global user.name ${GITHUB_NAME}
  - git tag ${TRAVIS_BUILD_NUMBER}
  - git push -q ${REPO} --tags
deploy:
  provider: releases
  api_key:
    secure: T3u0BqnXQ1MYMNdNdT+SNGYWGyPivrZMKnUIbWPZQGs001kq18BpC5WLabhH4+EfZ1P9j1hRHLUHsEP7QDjPeNPEtWFLNq51z+vPKx18eb6d0yUHHCWHGknP8NXWF7+buaQKZeJ05AzwkegnADumUOm+mqY249KSnlt0gFRaTWIAXUY8KOZP32Rq+pCE1yS7GsO7se27HtQw31qB9TEyEQYMU00pY/THqV4wHvO+9QHyFiv9MtbuTX+e4PEdA/xQpPv8qMX9BegppzX+Vz9Lughe77XWWJuOTqlcwqbj6M2Dao1KIlE4fzBN0zgdIApmATDzVdx7vthZdIFip2eRODlw9YKz0lX+gj8cuDw5uUZ4JTw5P5mkH9X0EDTv3h2nQw2A0qkYy3MGFhsSIwLJBeDkKQrUa/pylsPaYNwQUCegM3Sj/2wdN2IcllDUs7p5OOf4yhGRUUYR1JTocsZ3XcyzVlOsBXO2RJs9E6DqY9KUiEZG4NlQEo0DpYQrHR15r2Qhv8WmmxPaqBOO6wv21IpLsmf1t54PHIoBeVUI2qvjKuOBWX6XrljFL5iIYhIAmgjigggUmetJRNp1qbJQYBk6tSpsosMDnXEFHxtJXnomcpiZj0pbGGjWFREHxIDBqh0uLPk+NyD5RnI2+nVladEXoSdWnQCfQ4dYZy73bdI=
  file:
  - HMCL/build/libs/HMCL-${HMCL_VERSION_ROOT}.${TRAVIS_BUILD_NUMBER}.jar
  - HMCL/build/libs/HMCL-${HMCL_VERSION_ROOT}.${TRAVIS_BUILD_NUMBER}.exe
  - HMCL/build/libs/HMCL-${HMCL_VERSION_ROOT}.${TRAVIS_BUILD_NUMBER}-MacOSApp.zip
  on:
    repo: huanghongxun/HMCL
    tags: false
  skip_cleanup: true
install: echo "skip 'gradle assemble' step"
script: gradle build --continue --info --stacktrace
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
